### ISSUE TITLE
Status indicator issue

### ISSUE THREAD

**Issue by avive** [spacemeshos/dash-frontend#61]
1. Go to https://dash.spacemesh.io/
Result: status is orange not green.
2. Reload the page.
Result: status goes green.

Expected: status to go green on first load.

**Comment by Primaveralina** [comment]
@avive: not sure what’s the source of the issue but assuming devnet210 is healthy there’s the following issue in the dash frontend: go to dash, switch to net 210 from the drop down - result: status traffic light is read and turns orange after a while. expected green.

**Comment by Motzart** [comment]
status is orange because when we load page we have little delay before get data form server, and we need some status for this point - initial color(it can't be green because it will be incorrect), if you look closely - when we load page we don't have any dates, so the color at the beginning is orange

**Comment by avive** [comment]
I'm not sure this is the issue. The issue was that when devnet 210 was 2nd on the list and you needed to access it via the drop-down then it would turn green after a long time. The default network in the dash shows green quickly as expected. So it is likely a data loading issue when a new network is selected from the drop down. It is hard to reproduce now when devnet 210 is first and loads with the page.

**Comment by Motzart** [comment]
done

**Comment by avive** [comment]
Is it deployed?

**Comment by Primaveralina** [comment]
In production
